'use strict';
// Keep canvas art readable when index.html is opened directly with file://.
// Generated data URLs use the document's origin; no fetch, server or platform switch.
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const art = {};
for (const [name, file, mime] of [
  ['battle', 'ui-battle-scene-v1.jpg', 'image/jpeg'],
  ['animals', 'ui-animal-atlas-v1.webp', 'image/webp'],
]) {
  art[name] = 'data:' + mime + ';base64,' + fs.readFileSync(path.join(root, 'assets', file)).toString('base64');
}
fs.writeFileSync(path.join(root, 'js/art_assets.js'),
  "'use strict';\n// Generated by tools/build_art_assets.js; source paintings are in assets/.\nvar GAME_ART = " + JSON.stringify(art) + ';\n');
console.log('Embedded battle and animal paintings for direct-file Canvas access');
